name: AI Trading Bot

on:
  schedule:
    - cron: '0 1 * * *'

  workflow_dispatch:

jobs:
  run-bot:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Library
        run: |
          pip install requests
          pip install yfinance
          pip install pandas
          pip install ta

      - name: Run Python File
        run: python bot_trading.py
